# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aidar/CLionProjects/BizierEditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aidar/CLionProjects/BizierEditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aidar/CLionProjects/BizierEditor/CMakeFiles /home/aidar/CLionProjects/BizierEditor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aidar/CLionProjects/BizierEditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BizierEditor

# Build rule for target.
BizierEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BizierEditor
.PHONY : BizierEditor

# fast build rule for target.
BizierEditor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/build
.PHONY : BizierEditor/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f imgui/CMakeFiles/imgui.dir/build.make imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/main.cpp.s
.PHONY : main.cpp.s

src/app/app.o: src/app/app.cpp.o
.PHONY : src/app/app.o

# target to build an object file
src/app/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/app/app.cpp.o
.PHONY : src/app/app.cpp.o

src/app/app.i: src/app/app.cpp.i
.PHONY : src/app/app.i

# target to preprocess a source file
src/app/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/app/app.cpp.i
.PHONY : src/app/app.cpp.i

src/app/app.s: src/app/app.cpp.s
.PHONY : src/app/app.s

# target to generate assembly for a file
src/app/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/app/app.cpp.s
.PHONY : src/app/app.cpp.s

src/base/PickingTexture.o: src/base/PickingTexture.cpp.o
.PHONY : src/base/PickingTexture.o

# target to build an object file
src/base/PickingTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/PickingTexture.cpp.o
.PHONY : src/base/PickingTexture.cpp.o

src/base/PickingTexture.i: src/base/PickingTexture.cpp.i
.PHONY : src/base/PickingTexture.i

# target to preprocess a source file
src/base/PickingTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/PickingTexture.cpp.i
.PHONY : src/base/PickingTexture.cpp.i

src/base/PickingTexture.s: src/base/PickingTexture.cpp.s
.PHONY : src/base/PickingTexture.s

# target to generate assembly for a file
src/base/PickingTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/PickingTexture.cpp.s
.PHONY : src/base/PickingTexture.cpp.s

src/base/base.o: src/base/base.cpp.o
.PHONY : src/base/base.o

# target to build an object file
src/base/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/base.cpp.o
.PHONY : src/base/base.cpp.o

src/base/base.i: src/base/base.cpp.i
.PHONY : src/base/base.i

# target to preprocess a source file
src/base/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/base.cpp.i
.PHONY : src/base/base.cpp.i

src/base/base.s: src/base/base.cpp.s
.PHONY : src/base/base.s

# target to generate assembly for a file
src/base/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/base.cpp.s
.PHONY : src/base/base.cpp.s

src/base/grid.o: src/base/grid.cpp.o
.PHONY : src/base/grid.o

# target to build an object file
src/base/grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/grid.cpp.o
.PHONY : src/base/grid.cpp.o

src/base/grid.i: src/base/grid.cpp.i
.PHONY : src/base/grid.i

# target to preprocess a source file
src/base/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/grid.cpp.i
.PHONY : src/base/grid.cpp.i

src/base/grid.s: src/base/grid.cpp.s
.PHONY : src/base/grid.s

# target to generate assembly for a file
src/base/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/grid.cpp.s
.PHONY : src/base/grid.cpp.s

src/base/instance.o: src/base/instance.cpp.o
.PHONY : src/base/instance.o

# target to build an object file
src/base/instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/instance.cpp.o
.PHONY : src/base/instance.cpp.o

src/base/instance.i: src/base/instance.cpp.i
.PHONY : src/base/instance.i

# target to preprocess a source file
src/base/instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/instance.cpp.i
.PHONY : src/base/instance.cpp.i

src/base/instance.s: src/base/instance.cpp.s
.PHONY : src/base/instance.s

# target to generate assembly for a file
src/base/instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/base/instance.cpp.s
.PHONY : src/base/instance.cpp.s

src/primitives/BizierCurve.o: src/primitives/BizierCurve.cpp.o
.PHONY : src/primitives/BizierCurve.o

# target to build an object file
src/primitives/BizierCurve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/BizierCurve.cpp.o
.PHONY : src/primitives/BizierCurve.cpp.o

src/primitives/BizierCurve.i: src/primitives/BizierCurve.cpp.i
.PHONY : src/primitives/BizierCurve.i

# target to preprocess a source file
src/primitives/BizierCurve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/BizierCurve.cpp.i
.PHONY : src/primitives/BizierCurve.cpp.i

src/primitives/BizierCurve.s: src/primitives/BizierCurve.cpp.s
.PHONY : src/primitives/BizierCurve.s

# target to generate assembly for a file
src/primitives/BizierCurve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/BizierCurve.cpp.s
.PHONY : src/primitives/BizierCurve.cpp.s

src/primitives/Line.o: src/primitives/Line.cpp.o
.PHONY : src/primitives/Line.o

# target to build an object file
src/primitives/Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/Line.cpp.o
.PHONY : src/primitives/Line.cpp.o

src/primitives/Line.i: src/primitives/Line.cpp.i
.PHONY : src/primitives/Line.i

# target to preprocess a source file
src/primitives/Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/Line.cpp.i
.PHONY : src/primitives/Line.cpp.i

src/primitives/Line.s: src/primitives/Line.cpp.s
.PHONY : src/primitives/Line.s

# target to generate assembly for a file
src/primitives/Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BizierEditor.dir/build.make CMakeFiles/BizierEditor.dir/src/primitives/Line.cpp.s
.PHONY : src/primitives/Line.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BizierEditor"
	@echo "... imgui"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/app/app.o"
	@echo "... src/app/app.i"
	@echo "... src/app/app.s"
	@echo "... src/base/PickingTexture.o"
	@echo "... src/base/PickingTexture.i"
	@echo "... src/base/PickingTexture.s"
	@echo "... src/base/base.o"
	@echo "... src/base/base.i"
	@echo "... src/base/base.s"
	@echo "... src/base/grid.o"
	@echo "... src/base/grid.i"
	@echo "... src/base/grid.s"
	@echo "... src/base/instance.o"
	@echo "... src/base/instance.i"
	@echo "... src/base/instance.s"
	@echo "... src/primitives/BizierCurve.o"
	@echo "... src/primitives/BizierCurve.i"
	@echo "... src/primitives/BizierCurve.s"
	@echo "... src/primitives/Line.o"
	@echo "... src/primitives/Line.i"
	@echo "... src/primitives/Line.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

